using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessLayer
{
    public static class ASCIIArt
    {
        public static string Dog1 = "     |\\_/|                  \r\n     | @ @   Woof! \r\n     |   <>              _  \r\n     |  _/\\------____ ((| |))\r\n     |               `--' |   \r\n ____|_       ___|   |___.' \r\n/_/_____/____/_______|\r\n\r\n";

        public static string Dog2 = "         __\r\n        /  \\\r\n       / ..|\\\r\n      (_\\  |_)\r\n      /  \\@' \r\n     /     \\\r\n_   /  `   |\r\n\\\\/  \\  | _\\\r\n \\   /_ || \\\\_\r\n  \\____)|_) \\_)\r\n";

        public static string Dog3 = "         .--.             .---.\r\n        /:.  '.         .' ..  '._.---.\r\n       /:::-.  \\.-\"\"\"-;` .-:::.     .::\\\r\n      /::'|  `\\/  _ _  \\'   `\\:'   ::::|\r\n  __.'    |   /  (o|o)  \\     `'.   ':/\r\n /    .:. /   |   ___   |        '---'\r\n|    ::::'   /:  (._.) .:\\\r\n\\    .='    |:'        :::|\r\n `\"\"`       \\     .-.   ':/\r\n       \t     '---`|I|`---'\r\n                  '-'\r\n";

        public static string Dog4 = "   ,_____ ,\r\n  ,._ ,_. 7\\\r\n j `-'     /\r\n |o_, o    \\\r\n.`_y_`-,'   !\r\n|/   `, `._ `-,\r\n|_     \\   _.'*\\\r\n  >--,-'`-'*_*'``---.\r\n  |\\_* _*'-'         '\r\n /    `               \\\r\n \\.         _ .       /\r\n  '`._     /   )     /\r\n   \\  |`-,-|  /c-'7 /\r\n    ) \\ (_,| |   / (_\r\n   ((_/   ((_;)  \\_))) ";

        public static string Gerbil1 = "             /   \\                  /      \\\r\n             '      \\              /          \\\r\n            |       |Oo          o|            |\r\n            `    \\  |OOOo......oOO|   /        |\r\n             `    \\\\OOOOOOOOOOOOOOO\\//        /\r\n               \\ _o\\OOOOOOOOOOOOOOOO//. ___ /\r\n           ______OOOOOOOOOOOOOOOOOOOOOOOo.___\r\n            --- OO'* `OOOOOOOOOO'*  `OOOOO--\r\n                OO.   OOOOOOOOO'    .OOOOO o\r\n                `OOOooOOOOOOOOOooooOOOOOO'OOOo\r\n              .OO \"OOOOOOOOOOOOOOOOOOOO\"OOOOOOOo\r\n          __ OOOOOO`OOOOOOOOOOOOOOOO\"OOOOOOOOOOOOo\r\n         ___OOOOOOOO_\"OOOOOOOOOOO\"_OOOOOOOOOOOOOOOO\r\n           OOOOO^OOOO0`(____)/\"OOOOOOOOOOOOO^OOOOOO\r\n           OOOOO OO000/000000\\000000OOOOOOOO OOOOOO\r\n           OOOOO O0000000000000000 ppppoooooOOOOOO\r\n           `OOOOO 0000000000000000 QQQQ \"OOOOOOO\"\r\n            o\"OOOO 000000000000000oooooOOoooooooO'\r\n            OOo\"OOOO.00000000000000000000OOOOOOOO'\r\n           OOOOOO QQQQ 0000000000000000000OOOOOOO\r\n          OOOOOO00eeee00000000000000000000OOOOOOOO.\r\n         OOOOOOOO000000000000000000000000OOOOOOOOOO\r\n         OOOOOOOOO00000000000000000000000OOOOOOOOOO\r\n         `OOOOOOOOO000000000000000000000OOOOOOOOOOO\r\n           \"OOOOOOOO0000000000000000000OOOOOOOOOOO'\r\n             \"OOOOOOO00000000000000000OOOOOOOOOO\"\r\n  .ooooOOOOOOOo\"OOOOOOO000000000000OOOOOOOOOOO\"\r\n.OOO\"\"\"\"\"\"\"\"\"\".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOo\r\nOOO         QQQQO\"'                     `\"QQQQ\r\nOOO\r\n`OOo.\r\n  `\"OOOOOOOOOOOOoooooooo.";

        public static string Gerbil2 = "  _____             _____\r\n  / ___ \\           / ___ \\\r\n / /   \\ \\_________/ /   \\ \\\r\n| |     _/ \\    / \\_      | |\r\n \\     /  ^ \\  / ^  \\      /  \r\n  \\   |  | | \\/ | |  |    /\r\n  /   |  |O|    |O|  |    \\     \r\n |__ /------ @@ -------\\ __|   \r\n  \\     __   @@   __      /   \r\n   \\      \\______/       /\r\n    \\__     \\__/      __/        \r\n       \\_____________/\r\n";

        public static string Cat1 = "  |\\---/|\r\n   | ,_, |\r\n    \\_`_/-..----.\r\n ___/ `   ' ,\"\"+ \\  sk\r\n(__...'   __\\    |`.___.';\r\n  (_,...'(_,.`__)/'.....+\r\n";

        public static string Cat2 = "       \\`-._           __\r\n        \\\\  `-..____,.'  `.\r\n         :`.         /    \\`.\r\n         :  )       :      : \\\r\n          ;'        '   ;  |  :\r\n          )..      .. .:.`.;  :\r\n         /::...  .:::...   ` ;\r\n         ; _ '    __        /:\\\r\n         `:o>   /\\o_>      ;:. `.\r\n        `-`.__ ;   __..--- /:.   \\\r\n        === \\_/   ;=====_.':.     ;\r\n         ,/'`--'...`--....        ;\r\n              ;                    ;\r\n            .'                      ;\r\n          .'                        ;\r\n        .'     ..     ,      .       ;\r\n       :       ::..  /      ;::.     |\r\n      /      `.;::.  |       ;:..    ;\r\n     :         |:.   :       ;:.    ;\r\n     :         ::     ;:..   |.    ;\r\n      :       :;      :::....|     |\r\n      /\\     ,/ \\      ;:::::;     ;\r\n    .:. \\:..|    :     ; '.--|     ;\r\n   ::.  :''  `-.,,;     ;'   ;     ;\r\n.-'. _.'\\      / `;      \\,__:      \\\r\n`---'    `----'   ;      /    \\,.,,,/\r\n                   `----`             ";

        public static string Fish1 = " o\r\no      ______/~/~/~/__           /((\r\n  o  // __            ====__    /_((\r\n o  //  @))       ))))      ===/__((\r\n    ))           )))))))        __((\r\n    \\\\     \\)     ))))    __===\\ _((\r\n     \\\\_______________====      \\_((\r\n                                 \\((\r\n";

        public static string Title = " /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\ \r\n( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )\r\n > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ < \r\n /\\_/\\    ____  _____ _____       _______  ______ _   _    _    _   _  ____ _____    /\\_/\\ \r\n( o.o )  |  _ \\| ____|_   _|     | ____\\ \\/ / ___| | | |  / \\  | \\ | |/ ___| ____|  ( o.o )\r\n > ^ <   | |_) |  _|   | |       |  _|  \\  / |   | |_| | / _ \\ |  \\| | |  _|  _|     > ^ < \r\n /\\_/\\   |  __/| |___  | |       | |___ /  \\ |___|  _  |/ ___ \\| |\\  | |_| | |___    /\\_/\\ \r\n( o.o )  |_|   |_____| |_|       |_____/_/\\_\\____|_| |_/_/   \\_\\_| \\_|\\____|_____|  ( o.o )\r\n > ^ <                                                                               > ^ < \r\n /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\  /\\_/\\ \r\n( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )( o.o )\r\n > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ <  > ^ < ";
    }
}
